### ISSUE TITLE
[Feature] Allow Min  / Max to be specified in the incoming message

### ISSUE THREAD

**Issue by hamsando** [bartbutenaers/node-red-contrib-ui-heatmap#8] opened 2021-12-07 00:51 UTC
Any chance of adding in the ability to set the Min/Max values via the incoming message?  

I'd offer to do submit some code for this, but I see you actually already had a branch that did this, but just didn't integrate it into the main branch.

**Comment by bartbutenaers** [comment] 2021-12-08 17:24
Hi @hamsando,

I had completely forgotten about that branch.  Will need to have a good look at it first, before I merge it into the master branch.  Because I don't know anymore whether that feature was well tested at the time being.

Will try to do that in the next days, and get back to you.
Don't hesistate to send me a reminder next week, because that would mean I have forgotten about it ;-)

Bart

**Comment by bartbutenaers** [comment] 2021-12-08 20:14
@hamsando,

It seems to me that the branch is fine, so I have merged it into the master.  I did a quick test and it seems ok to me.

But it would be a great help for me if you could do also some extra tests.  You can install the version directly from this Github repo (from within your .node-red folder):
```
npm install bartbutenaers/node-red-contrib-ui-heatmap
```
Once you have confirmed, I will publish it on NPM.
Thanks!!
Bart

**Comment by hamsando** [comment] 2021-12-09 04:10
I popped it onto my test production server - replacing the version of your node that I'd edited manually to add the functionality - and it didn't miss a beat. I played around a bit with some min/max values and it seems to work as I'd expect.

The one thing you need to do is update the documentation to indicate that if you do not check "specify minimum and maximum value", then you can send msg.minimum and msg.maximum. 

Thanks for the quick response.

**Comment by bartbutenaers** [comment] 2021-12-09 06:17
@hamsando,
Thanks for the testing!!

About the documentation.  Can you specify that a bit more in detail please?
Because I had updated - at the time being - this in my documentation:
+ Info panel:

   ![image](https://user-images.githubusercontent.com/14224149/145344121-b68155e1-9978-4530-85e8-b7b39ddf5570.png)

+ Readme page:

   ![image](https://user-images.githubusercontent.com/14224149/145344274-0fb793e2-ebcd-4227-816d-b500bc2ae4f9.png)

Is that not enough information, or not clear perhaps, or do you mean somewhere else?

**Comment by hamsando** [comment] 2021-12-09 07:42
My bad. I was talking about help within NR when you select the node. But it was my error, I needed to clear the browser cache to get it to show the new text. 

So in summary, everything is fine.

**Comment by bartbutenaers** [comment] 2021-12-09 22:21
Hi @hamsando,

Version 2.2.1 is now available:

![image](https://user-images.githubusercontent.com/14224149/145484984-47b3a1c2-de06-4bcb-8da4-bf5213d7c024.png)

**Closed as completed by bartbutenaers** 2021-12-09 22:21 UTC
Labels: enhancement
